%Applying signal preprocessing on EH signals
function out = hospital_preprocess_esignals(data_struct)
  %Get patients and videos number
  [patients, videos] = size(data_struct);
  %Load filter coeffs
  FIRs = load('FIRs.mat');
  %Set sampling frequency and processing window
  Fs = 200;
  window_gsr     = 4;
  downsample_gsr = 20; % Fs' = 200/20 = 10Hz
  for j = 1:patients
    for i = 1:videos-1
      fprintf('Patient %d, Video %d filtering...\n',j, i);
      %Neutro
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered = ...
%           filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Neutro.raw.gsr);
% 	  data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_dn = ...
%           downsample(data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered,downsample_gsr);
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_dn_sm = ...
%           movmedian(movmean(data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_dn,...
%                            (Fs/downsample_gsr)),(Fs/downsample_gsr)/2);
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_tonic = ... 
%           movmedian(data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered,[Fs*window_gsr Fs*window_gsr]);
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_phasic = ...
%           data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered - ...
%                  data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_tonic;
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_tonic_dn = ... 
%           movmedian(data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_dn,... 
%           [Fs*window_gsr/downsample_gsr Fs*window_gsr/downsample_gsr]);
%       data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_phasic_dn = ...
%           data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_dn - ...
%                  data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered_tonic_dn;
				 
      %Video
      data_struct{j,i}.EH.Video.raw.gsr_uS_filtered = ...
          filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Video.raw.gsr);
	  data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn = ...
          downsample(data_struct{j,i}.EH.Video.raw.gsr_uS_filtered,downsample_gsr);
      data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn_sm = ...
          movmedian(movmean(data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn,...
                           (Fs/downsample_gsr)),(Fs/downsample_gsr)/2);
%       data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_tonic = ... 
%           movmedian(data_struct{j,i}.EH.Video.raw.gsr_uS_filtered,[Fs*window_gsr Fs*window_gsr]);
%       data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_phasic = ...
%           data_struct{j,i}.EH.Video.raw.gsr_uS_filtered - ...
%                  data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_tonic;
%       data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_tonic_dn = ... 
%           movmedian(data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn,...
%           [Fs*window_gsr/downsample_gsr Fs*window_gsr/downsample_gsr]);
%       data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_phasic_dn = ...
%           data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn - ...
%                  data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_tonic_dn;
				 
      %Labels
      data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered = ...
          filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Labels.raw.gsr);
	  data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_dn = ...
          downsample(data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered,downsample_gsr);
      data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_dn_sm = ...
          movmedian(movmean(data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_dn,...
                           (Fs/downsample_gsr)),(Fs/downsample_gsr)/2);      
%       data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_tonic = ... 
%           movmedian(data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered,[Fs*window_gsr Fs*window_gsr]);
%       data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_phasic = ...
%           data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered - ...
%                  data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_tonic;
%       data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_tonic_dn = ... 
%           movmedian(data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_dn,...
%           [Fs*window_gsr/downsample_gsr Fs*window_gsr/downsample_gsr]);
%       data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_phasic_dn = ...
%           data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_dn - ...
%                  data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered_tonic_dn;
				 
      %Recovery
%       if(length(data_struct{j,i}.EH.Recovery.raw.gsr)>(3*length(FIRs.Coeffs_GSR)))
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered = ...
%           filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Recovery.raw.gsr);
%       elseif(length(data_struct{j,i}.EH.Recovery.raw.gsr)>(3*length(FIRs.Coeffs_GSR_smaller)))
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered = ...
%           filtfilt(FIRs.Coeffs_GSR_smaller,1,data_struct{j,i}.EH.Recovery.raw.gsr);
%       else
%         %Not filtering provided
%       end
      data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered = ...
          filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Recovery.raw.gsr);
	  data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_dn = ...
          downsample(data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered,downsample_gsr);
      data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_dn_sm = ...
          movmedian(movmean(data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_dn,...
                           (Fs/downsample_gsr)),(Fs/downsample_gsr)/2); 
                       
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_tonic = ... 
%           movmedian(data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered,[Fs*window_gsr Fs*window_gsr]);
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_phasic = ...
%           data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered - ...
%                  data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_tonic;
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_tonic_dn = ... 
%           movmedian(data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_dn,...
%           [Fs*window_gsr/downsample_gsr Fs*window_gsr/downsample_gsr]);
%       data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_phasic_dn = ...
%           data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_dn - ...
%                  data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered_tonic_dn;
				  
      %BVP 
%       %Neutro
%       [data_struct{j,i}.EH.Neutro.raw.hr,data_struct{j,i}.EH.Neutro.raw.bvp_filt] = ...
%           getHeartRate_eh(data_struct{j,i}.EH.Neutro.raw.bvp,0);
%       data_struct{j,i}.EH.Neutro.raw.hrv = diff(data_struct{j,i}.EH.Neutro.raw.hr);
%       %Video
%       [data_struct{j,i}.EH.Video.raw.hr,data_struct{j,i}.EH.Video.raw.bvp_filt] = ...
%           getHeartRate_eh(data_struct{j,i}.EH.Video.raw.bvp,0);
%       data_struct{j,i}.EH.Video.raw.hrv = diff(data_struct{j,i}.EH.Video.raw.hr);
%       %Labels
%       [data_struct{j,i}.EH.Labels.raw.hr,data_struct{j,i}.EH.Labels.raw.bvp_filt] = ...
%           getHeartRate_eh(data_struct{j,i}.EH.Labels.raw.bvp,0);
%       data_struct{j,i}.EH.Labels.raw.hrv = diff(data_struct{j,i}.EH.Labels.raw.hr);
%       %Recovery
%       [data_struct{j,i}.EH.Recovery.raw.hr,data_struct{j,i}.EH.Recovery.raw.bvp_filt] = ...
%           getHeartRate_eh(data_struct{j,i}.EH.Recovery.raw.bvp,1);
%       data_struct{j,i}.EH.Recovery.raw.hrv = diff(data_struct{j,i}.EH.Recovery.raw.hr);
      
%       data_struct{j,i}.EH.Neutro.raw.bvp_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Neutro.raw.bvp);
%       data_struct{j,i}.EH.Neutro.raw.bvp_filt = ...
%           data_struct{j,i}.EH.Neutro.raw.bvp_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Neutro.raw.bvp_filt,Fs);
      data_struct{j,i}.EH.Video.raw.bvp_filt = ...
          filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Video.raw.bvp);
      data_struct{j,i}.EH.Video.raw.bvp_filt = ...
          data_struct{j,i}.EH.Video.raw.bvp_filt - ...
          BVP_removebaselinewander_signal(data_struct{j,i}.EH.Video.raw.bvp_filt,Fs);
      data_struct{j,i}.EH.Labels.raw.bvp_filt = ...
          filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Labels.raw.bvp);
      data_struct{j,i}.EH.Labels.raw.bvp_filt = ...
          data_struct{j,i}.EH.Labels.raw.bvp_filt - ...
          BVP_removebaselinewander_signal(data_struct{j,i}.EH.Labels.raw.bvp_filt,Fs);
       data_struct{j,i}.EH.Recovery.raw.bvp_filt = ...
          data_struct{j,i}.EH.Recovery.raw.bvp_filt - ...
          BVP_removebaselinewander_signal(data_struct{j,i}.EH.Recovery.raw.bvp_filt,Fs);
      
%       if(length(data_struct{j,i}.EH.Recovery.raw.bvp)>(3*length(FIRs.Coeffs_BVP)))
%         data_struct{j,i}.EH.Recovery.raw.bvp_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Recovery.raw.bvp);
%       elseif((length(data_struct{j,i}.EH.Recovery.raw.bvp)>(3*length(FIRs.Coeffs_BVP_smaller))))
%         data_struct{j,i}.EH.Recovery.raw.bvp_filt = ...
%           filtfilt(FIRs.Coeffs_BVP_smaller,1,data_struct{j,i}.EH.Recovery.raw.bvp);
%       else
%         %Not filtering provided
%         data_struct{j,i}.EH.Recovery.raw.bvp_filt = smooth(data_struct{j,i}.EH.Recovery.raw.bvp,Fs/2);
%       end
%       
%       data_struct{j,i}.EH.Recovery.raw.bvp_filt = ...
%           data_struct{j,i}.EH.Recovery.raw.bvp_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Recovery.raw.bvp_filt,Fs); 
        
        %AGC
%       iterations = 2;
%       for k=1:iterations
%       data_struct{j,i}.EH.Neutro.raw.bvp = ...
%           BVP_enhancePeaks_signal(data_struct{j,i}.EH.Neutro.raw.bvp);
%       data_struct{j,i}.EH.Video.raw.bvp = ...
%           BVP_enhancePeaks_signal(data_struct{j,i}.EH.Video.raw.bvp);
%       data_struct{j,i}.EH.Labels.raw.bvp = ...
%           BVP_enhancePeaks_signal(data_struct{j,i}.EH.Labels.raw.bvp);
%       data_struct{j,i}.EH.Recovery.raw.bvp = ...
%           BVP_enhancePeaks_signal(data_struct{j,i}.EH.Recovery.raw.bvp);
%       end

      %ACC 
%       data_struct{j,i}.EH.Neutro.raw.acc1_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Neutro.raw.acc1);
%       data_struct{j,i}.EH.Neutro.raw.acc1_filt = ...
%           data_struct{j,i}.EH.Neutro.raw.acc1_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Neutro.raw.acc1_filt,Fs);
%       data_struct{j,i}.EH.Neutro.raw.acc2_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Neutro.raw.acc2);
%       data_struct{j,i}.EH.Neutro.raw.acc2_filt = ...
%           data_struct{j,i}.EH.Neutro.raw.acc2_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Neutro.raw.acc2_filt,Fs);
%       data_struct{j,i}.EH.Neutro.raw.acc3_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Neutro.raw.acc3);
%       data_struct{j,i}.EH.Neutro.raw.acc3_filt = ...
%           data_struct{j,i}.EH.Neutro.raw.acc3_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Neutro.raw.acc3_filt,Fs);
%       
%       
%       data_struct{j,i}.EH.Video.raw.acc1_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Video.raw.acc1);
%       data_struct{j,i}.EH.Video.raw.acc1_filt = ...
%           data_struct{j,i}.EH.Video.raw.acc1_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Video.raw.acc1_filt,Fs);
%       data_struct{j,i}.EH.Video.raw.acc2_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Video.raw.acc2);
%       data_struct{j,i}.EH.Video.raw.acc2_filt = ...
%           data_struct{j,i}.EH.Video.raw.acc2_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Video.raw.acc2_filt,Fs);
%       data_struct{j,i}.EH.Video.raw.acc3_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Video.raw.acc3);
%       data_struct{j,i}.EH.Video.raw.acc3_filt = ...
%           data_struct{j,i}.EH.Video.raw.acc3_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Video.raw.acc3_filt,Fs);
%       
% 
%        data_struct{j,i}.EH.Labels.raw.acc1_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Labels.raw.acc1);
%       data_struct{j,i}.EH.Labels.raw.acc1_filt = ...
%           data_struct{j,i}.EH.Labels.raw.acc1_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Labels.raw.acc1_filt,Fs);
%       data_struct{j,i}.EH.Labels.raw.acc2_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Labels.raw.acc2);
%       data_struct{j,i}.EH.Labels.raw.acc2_filt = ...
%           data_struct{j,i}.EH.Labels.raw.acc2_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Labels.raw.acc2_filt,Fs);
%       data_struct{j,i}.EH.Labels.raw.acc3_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Labels.raw.acc3);
%       data_struct{j,i}.EH.Labels.raw.acc3_filt = ...
%           data_struct{j,i}.EH.Labels.raw.acc3_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Labels.raw.acc3_filt,Fs);     
%       
%       
%       if(length(data_struct{j,i}.EH.Recovery.raw.acc1)>(3*length(FIRs.Coeffs_BVP)))
%         data_struct{j,i}.EH.Recovery.raw.acc1_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Recovery.raw.acc1);
%         data_struct{j,i}.EH.Recovery.raw.acc2_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Recovery.raw.acc2);
%         data_struct{j,i}.EH.Recovery.raw.acc3_filt = ...
%           filtfilt(FIRs.Coeffs_BVP,1,data_struct{j,i}.EH.Recovery.raw.acc3);
%       elseif((length(data_struct{j,i}.EH.Recovery.raw.bvp)>(3*length(FIRs.Coeffs_BVP_smaller))))
%         data_struct{j,i}.EH.Recovery.raw.acc1_filt = ...
%           filtfilt(FIRs.Coeffs_BVP_smaller,1,data_struct{j,i}.EH.Recovery.raw.acc1);
%         data_struct{j,i}.EH.Recovery.raw.acc2_filt = ...
%           filtfilt(FIRs.Coeffs_BVP_smaller,1,data_struct{j,i}.EH.Recovery.raw.acc2);
%         data_struct{j,i}.EH.Recovery.raw.acc3_filt = ...
%           filtfilt(FIRs.Coeffs_BVP_smaller,1,data_struct{j,i}.EH.Recovery.raw.acc3);
%       else
%         %Not filtering provided
%         data_struct{j,i}.EH.Recovery.raw.acc1_filt = smooth(data_struct{j,i}.EH.Recovery.raw.acc1,Fs/2);
%         data_struct{j,i}.EH.Recovery.raw.acc2_filt = smooth(data_struct{j,i}.EH.Recovery.raw.acc2,Fs/2);
%         data_struct{j,i}.EH.Recovery.raw.acc3_filt = smooth(data_struct{j,i}.EH.Recovery.raw.acc3,Fs/2);
%       end
%       
%       data_struct{j,i}.EH.Recovery.raw.acc1_filt = ...
%           data_struct{j,i}.EH.Recovery.raw.acc1_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Recovery.raw.acc1_filt,Fs);
%       data_struct{j,i}.EH.Recovery.raw.acc2_filt = ...
%           data_struct{j,i}.EH.Recovery.raw.acc2_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Recovery.raw.acc2_filt,Fs);
%       data_struct{j,i}.EH.Recovery.raw.acc3_filt = ...
%           data_struct{j,i}.EH.Recovery.raw.acc3_filt - ...
%           BVP_removebaselinewander_signal(data_struct{j,i}.EH.Recovery.raw.acc3_filt,Fs);
      
      %SKT 
      %%Neutro
%       data_struct{j,i}.EH.Neutro.raw.skt_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Neutro.raw.skt);
%       data_struct{j,i}.EH.Neutro.raw.skt_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Neutro.raw.skt_filt,downsample_gsr);
%       data_struct{j,i}.EH.Neutro.raw.skt_filt_dn_sm = ...
%           movmedian(movmean(data_struct{j,i}.EH.Neutro.raw.skt_filt_dn,...
%                            (Fs/downsample_gsr)),(Fs/downsample_gsr)/2); 
%       %%Video
%       data_struct{j,i}.EH.Video.raw.skt_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Video.raw.skt);
%       data_struct{j,i}.EH.Video.raw.skt_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Video.raw.skt_filt,downsample_gsr);
%       data_struct{j,i}.EH.Video.raw.skt_filt_dn_sm = ...
%           movmedian(movmean(data_struct{j,i}.EH.Video.raw.skt_filt_dn,...
%                            (Fs/downsample_gsr)),(Fs/downsample_gsr)/2); 
%       %%Labels
%       data_struct{j,i}.EH.Labels.raw.skt_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Labels.raw.skt);
%       data_struct{j,i}.EH.Labels.raw.skt_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Labels.raw.skt_filt,downsample_gsr);
%       data_struct{j,i}.EH.Labels.raw.skt_filt_dn_sm = ...
%           movmedian(movmean(data_struct{j,i}.EH.Labels.raw.skt_filt_dn,...
%                            (Fs/downsample_gsr)),(Fs/downsample_gsr)/2); 
      %%Recovery
%       data_struct{j,i}.EH.Recovery.raw.skt_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Recovery.raw.skt);
%       data_struct{j,i}.EH.Recovery.raw.skt_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Recovery.raw.skt_filt,downsample_gsr);
      
      %EMG adjust length
      %%Neutro
%       data_struct{j,i}.EH.Neutro.raw.emg_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Neutro.raw.emg);
%       data_struct{j,i}.EH.Neutro.raw.emg_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Neutro.raw.emg_filt,downsample_gsr);
%       %%Video
%       data_struct{j,i}.EH.Video.raw.emg_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Video.raw.emg);
%       data_struct{j,i}.EH.Video.raw.emg_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Video.raw.emg_filt,downsample_gsr);
%       %%Labels
%       data_struct{j,i}.EH.Labels.raw.emg_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Labels.raw.emg);
%       data_struct{j,i}.EH.Labels.raw.emg_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Labels.raw.emg_filt,downsample_gsr);
      %%Recovery
%       data_struct{j,i}.EH.Recovery.raw.emg_filt = filtfilt(FIRs.Coeffs_GSR,1,data_struct{j,i}.EH.Recovery.raw.emg);
%       data_struct{j,i}.EH.Recovery.raw.emg_filt_dn = ...
%           downsample(data_struct{j,i}.EH.Recovery.raw.emg_filt,downsample_gsr);
      
%       
%       f = figure;
%       set(gcf, 'Units', 'Normalized', 'OuterPosition', [0 0 1 1]);
%       f.Name = "patient " + j +  " / Trial" + i;
%       subplot(3,1,1);
% %       len_ppg = length(data_struct{j,i}.EH.Neutro.raw.bvp_filt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Neutro.raw.bvp_filt);
% %       ylabel('a.u.')
% %       title("patient " + j +  " / Trial" + i + " Neutro");
% %       subplot(4,1,2);
%       len_ppg = length(data_struct{j,i}.EH.Video.raw.bvp_filt);
%       t = linspace(0,len_ppg/Fs,len_ppg);
%       plot(t,data_struct{j,i}.EH.Video.raw.bvp_filt);
%       ylabel('a.u.')
%       title("patient " + j +  " / Trial" + i + " Video");
% %       subplot(4,1,3);
% %       len_ppg = length(data_struct{j,i}.EH.Labels.raw.bvp_filt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Labels.raw.bvp_filt);
% %       ylabel('a.u.')
% %       title("patient " + j +  " / Trial" + i + " Labels");
% %       subplot(4,1,4);
% %       len_ppg = length(data_struct{j,i}.EH.Recovery.raw.bvp_filt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Recovery.raw.bvp_filt);
% %       ylabel('a.u.')
% %       title("patient " + j +  " / Trial" + i + " Recovery");
%       
% %       f = figure;
% %       f.Name = "GSR patient " + j +  " / Trial" + i;
% %       subplot(4,1,1);
% %       len_ppg = length(data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Neutro.raw.gsr_uS_filtered);
% %       ylabel('uSiemens.')
% %       title("patient " + j +  " / Trial" + i + " Neutro");
%       subplot(3,1,2);
%       len_ppg = length(data_struct{j,i}.EH.Video.raw.gsr_uS_filtered);
%       t = linspace(0,len_ppg/Fs,len_ppg);
%       plot(downsample(t,downsample_gsr),data_struct{j,i}.EH.Video.raw.gsr_uS_filtered_dn);
%       ylabel('uSiemens')
%       title("patient " + j +  " / Trial" + i + " Video");
% %       subplot(4,1,3);
% %       len_ppg = length(data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Labels.raw.gsr_uS_filtered);
% %       ylabel('uSiemens')
% %       title("patient " + j +  " / Trial" + i + " Labels");
% %       subplot(4,1,4);
% %       len_ppg = length(data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Recovery.raw.gsr_uS_filtered);
% %       ylabel('uSiemens')
% %       title("patient " + j +  " / Trial" + i + " Recovery");
%       
%       
% %       f = figure;
% %       f.Name = "SKT patient " + j +  " / Trial" + i;
% %       subplot(4,1,1);
% %       len_ppg = length(data_struct{j,i}.EH.Neutro.raw.skt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Neutro.raw.skt);
% %       ylabel('ºC')
% %       title("patient " + j +  " / Trial" + i + " Neutro");
%       subplot(3,1,3);
%       len_ppg = length(data_struct{j,i}.EH.Video.raw.skt_filt);
%       t = linspace(0,len_ppg/Fs,len_ppg);
%       plot(downsample(t,downsample_gsr),data_struct{j,i}.EH.Video.raw.skt_filt_dn);
%       ylabel('ºC')
%       title("patient " + j +  " / Trial" + i + " Video");
% %       subplot(4,1,3);
% %       len_ppg = length(data_struct{j,i}.EH.Labels.raw.skt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Labels.raw.skt);
% %       ylabel('ºC')
% %       title("patient " + j +  " / Trial" + i + " Labels");
% %       subplot(4,1,4);
% %       len_ppg = length(data_struct{j,i}.EH.Recovery.raw.skt);
% %       t = linspace(0,len_ppg/Fs,len_ppg);
% %       plot(t,data_struct{j,i}.EH.Recovery.raw.skt);
% %       ylabel('ºC')
% %       title("patient " + j +  " / Trial" + i + " Recovery");

      %Setting pre-processing Flag
      data_struct{j,i}.Filtered = 1;
    end
  end
  
  out = data_struct;
end